name: PyTorch-Tutorial

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
# Mostly used Python libs
  - python=3.10.4
  - autopep8=1.6.0
  - black=19.10b0
  - pip=22.1.2
  - numpy=1.22.3
  - scipy=1.7.3
  - pandas=1.4.3
  - matplotlib=3.5.1
  # - pip:
    # - tensorflow==2.0
# IPython modules
  - ipywidgets=7.6.5
  # - jupyterlab
  # - jupyterlab-git
  # - jupyterlab-nvdashboard
  # - jupyterlab-lsp
  # - python-language-server
# Machine learning modules
  - pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio=0.12.0
  # - pytorch=1.9
  # - pytorch-lightning
  # - torchvision
# GPU 
  - cudatoolkit=11.6 