name: PyTorch-Tutorial

channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
# Mostly used Python libs
  - python
  - autopep8
  - black
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  # - pip:
    # - tensorflow==2.0
# IPython modules
  - ipywidgets
  # - jupyterlab
  # - jupyterlab-git
  # - jupyterlab-nvdashboard
  # - jupyterlab-lsp
  # - python-language-server
# Machine learning modules
  - pytorch=1.11.0
  - torchvision
  - torchaudio
  # - pytorch=1.9
  # - pytorch-lightning
  # - torchvision
# GPU 
  - cudatoolkit=10.2